language: csharp
mono:
- latest
install:
- nuget restore
script:
- ./.ci.sh
env:
  secure: WFB1nNB9Ro+UBsuq81eqzUyQPJxz522sNX3wayyipujaIrTHG/lvprYp1FUGxMXJM13mdAs6Q9SO57n74s6UpV7zhGl4c5+nUFO4TxKR+6cjnss8QeYz905fh5c/ZhAxIXKHz5PQ9RsRUtw6JHo1bRIY1afald1it9qjrnhc7/jidd+bQXrzI2NzEfbeguvzlYDqzT+VzvuuqzMGJPk2B7uoGGemscY+jFSTN7xcphkV/LSviiyLqbyBWBm0X9f03e4Zg6CbSO4gyM0yIX4g6sGNMd50qsp0BvZzbIwAuFZLyvohCR9L9K5ASvGPhW7/wxMGdc7gShzFrdOvxKurxo26LdWw5SVxDcdvGbtpa+tMCVx4dOSkDiEy59pHxOnzK9rVHTsLrgYmKHgNEYQmyhz9NSL+PFOenoJn+/spXFBeAl9YeOMYM8yZZmlg2Wb8TtxTB89ofVzC+Ui8AjzqqhVl5Lc59JaFekU5un78VOD/6iPI3CpqgcYaVPf/tK0cNVP+7ESkw078iDVmFfWod/2mcq8ooeNCtB2FEvkkub0aasSmaFE8J3Mbj1cK/HXA42GH1buzhFHHGUWQQiAK1axKJx7+zSrTbCUeEsQFlhZGt5lMwO8HJSm6wecQE6/YXEcZehDDPTLih41uCFwiqrcj8LxfwBOAGmd1CuevefE=
